const initialState = [
    {
      id: '214',
      name: 'Vijayalakshmi Travels',
      type: 'A/C Seater/Sleeper(2+1)',
      depatureTime: '18:30 pm',
      arrivalTime: '06:15 am',
      fare: '1000',
      rating:4.6,
      people:1235,
      availseats:24,
      boardingPoints: ['Koyembedu', 'Ashok Pillar', 'Guindy', 'Tambaram'],
      droppingPoints: ['Salem', 'Erode', 'Erode ByPass'],
      seats: [
        { no: '1', isBooked: true },
        { no: '2', isBooked: true },
        { no: '3', isBooked: true },
        { no: '4', isBooked: false },
        { no: '5', isBooked: false },
        { no: '6', isBooked: true },
        { no: '7', isBooked: false },
        { no: '8', isBooked: true },
        { no: '9', isBooked: true },
        { no: '10', isBooked: true },
        { no: '11', isBooked: true },
        { no: '12', isBooked: true },
        { no: '13', isBooked: true },
        { no: '14', isBooked: true },
        { no: '15', isBooked: true },
        { no: '16', isBooked: true },
        { no: '17', isBooked: true },
        { no: '18', isBooked: true },
        { no: '19', isBooked: true },
        { no: '20', isBooked: true },
        { no: '21', isBooked: true },
        { no: '22', isBooked: true },
        { no: '23', isBooked: true },
        { no: '24', isBooked: true },
      ],
    },
    {
      id: '102',
  
      name: 'Night special Travels',
      type: 'A/C Sleeper(2+1)',
      depatureTime: '22:30 pm',
      arrivalTime: '08:15 am',
      fare: '1200',
      rating:4.2,
      people:2235,
      availseats:24,
      boardingPoints: ['Koyembedu', 'Ashok Pillar', 'Guindy', 'Tambaram'],
      droppingPoints: ['Salem', 'Erode', 'Erode ByPass'],
      seats: [
        { no: '1', isBooked: false },
        { no: '2', isBooked: true },
        { no: '3', isBooked: false },
        { no: '4', isBooked: false },
        { no: '5', isBooked: false },
        { no: '6', isBooked: true },
        { no: '7', isBooked: false },
        { no: '8', isBooked: true },
        { no: '9', isBooked: false },
        { no: '10', isBooked: true },
        { no: '11', isBooked: true },
        { no: '12', isBooked: true },
        { no: '13', isBooked: true },
        { no: '14', isBooked: true },
        { no: '15', isBooked: true },
        { no: '16', isBooked: true },
        { no: '17', isBooked: true },
        { no: '18', isBooked: true },
        { no: '19', isBooked: true },
        { no: '20', isBooked: true },
        { no: '21', isBooked: true },
        { no: '22', isBooked: true },
        { no: '23', isBooked: true },
        { no: '24', isBooked: true },
      ],
    },
    {
      id: '786',
  
      name: 'Go Tour Travels',
      type: 'A/C Seater/Sleeper',
      depatureTime: '23:30 pm',
      arrivalTime: '09:15 am',
      rating:4.1,
      people:1785,
      fare: '900',
      availseats:24,
      boardingPoints: ['Koyembedu', 'Ashok Pillar', 'Guindy', 'Tambaram'],
      droppingPoints: ['Salem', 'Erode', 'Erode ByPass'],
      seats: [
        { no: '1', isBooked: true },
        { no: '2', isBooked: true },
        { no: '3', isBooked: true },
        { no: '4', isBooked: true },
        { no: '5', isBooked: true },
        { no: '6', isBooked: true },
        { no: '7', isBooked: true },
        { no: '8', isBooked: true },
        { no: '9', isBooked: true },
        { no: '10', isBooked: true },
        { no: '11', isBooked: true },
        { no: '12', isBooked: true },
        { no: '13', isBooked: true },
        { no: '14', isBooked: true },
        { no: '15', isBooked: true },
        { no: '16', isBooked: true },
        { no: '17', isBooked: true },
        { no: '18', isBooked: true },
        { no: '19', isBooked: true },
        { no: '20', isBooked: true },
        { no: '21', isBooked: true },
        { no: '22', isBooked: true },
        { no: '23', isBooked: true },
        { no: '24', isBooked: true },
      ],
    },
    {
      id: '618',
      name: 'Morning Star Travels',
      type: 'Seater/Sleeper(2+1)',
      depatureTime: '01:30 am',
      arrivalTime: '11:15 am',
      fare: '800',
      rating:4.6,
      people:1905,
      availseats:24,
      boardingPoints: ['Koyembedu', 'Ashok Pillar', 'Guindy', 'Tambaram'],
      droppingPoints: ['Salem', 'Erode', 'Erode ByPass'],
      seats: [
        { no: '1', isBooked: false },
        { no: '2', isBooked: false },
        { no: '3', isBooked: false },
        { no: '4', isBooked: false },
        { no: '5', isBooked: false },
        { no: '6', isBooked: false },
        { no: '7', isBooked: false },
        { no: '8', isBooked: false },
        { no: '9', isBooked: false },
        { no: '10', isBooked: false },
        { no: '11', isBooked: true },
        { no: '12', isBooked: true },
        { no: '13', isBooked: true },
        { no: '14', isBooked: true },
        { no: '15', isBooked: true },
        { no: '16', isBooked: true },
        { no: '17', isBooked: true },
        { no: '18', isBooked: true },
        { no: '19', isBooked: true },
        { no: '20', isBooked: true },
        { no: '21', isBooked: true },
        { no: '22', isBooked: true },
        { no: '23', isBooked: true },
        { no: '24', isBooked: true },
      ],
    },
    {
      id: '188',
      name: 'Sanju Travels',
      type: 'A/C Seater/Sleeper(2+1)',
      depatureTime: '19:30 pm',
      arrivalTime: '05:15 am',
      fare: '1100',
      rating:4.3,
      people:3235,
      availseats:24,
      boardingPoints: ['Koyembedu', 'Ashok Pillar', 'Guindy', 'Tambaram'],
      droppingPoints: ['Salem', 'Erode', 'Erode ByPass'],
      seats: [
        { no: '1', isBooked: false },
        { no: '2', isBooked: true },
        { no: '3', isBooked: false },
        { no: '4', isBooked: false },
        { no: '5', isBooked: false },
        { no: '6', isBooked: false },
        { no: '7', isBooked: false },
        { no: '8', isBooked: false },
        { no: '9', isBooked: false },
        { no: '10', isBooked: false },
        { no: '11', isBooked: true },
        { no: '12', isBooked: true },
        { no: '13', isBooked: true },
        { no: '14', isBooked: true },
        { no: '15', isBooked: true },
        { no: '16', isBooked: true },
        { no: '17', isBooked: true },
        { no: '18', isBooked: true },
        { no: '19', isBooked: true },
        { no: '20', isBooked: true },
        { no: '21', isBooked: true },
        { no: '22', isBooked: true },
        { no: '23', isBooked: true },
        { no: '24', isBooked: true },
      ],
    },
  ];
 const Bus =  (state = initialState) => {
    return state;
  };
  export default Bus;